export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'

export const QUESTION_NUMBER_REQUEST = 'QUESTION_NUMBER_REQUEST'
export const QUESTION_NUMBER_SUCCESS = 'QUESTION_NUMBER_SUCCESS'
export const QUESTION_NUMBER_FAIL = 'QUESTION_NUMBER_FAIL'

export const OPTION_PICK_REQUEST = 'OPTION_PICK_REQUEST'
export const OPTION_PICK_SUCCESS = 'OPTION_PICK_SUCCESS'
export const OPTION_PICK_FAIL = 'OPTION_PICK_FAIL'
export const OPTION_PICK_RESET = 'OPTION_PICK_RESET'

