export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_TEST_SUBMIT_REQUEST = 'USER_TEST_SUBMIT_REQUEST'
export const USER_TEST_SUBMIT_SUCCESS = 'USER_TEST_SUBMIT_SUCCESS'
export const USER_TEST_SUBMIT_FAIL = 'USER_TEST_SUBMIT_FAIL'